name: Root trigger

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_affected:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.result }}
    name: Dispatch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        uses: ng-easy/npm-setup@v1.7.2
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.1
        id: affected
        with:
          script: |
            $tags = npm run --silent nx print-affected -- --select=projects --type=app --base=origin/main~1 --head=main
            return ConvertTo-Json $tags.Trim().Split(" ")
  dispatch_event:
    needs: [build_affected]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{fromJson(needs.build_affected.outputs.affected)}}
    steps:
      - name: Publish Event
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          event-type: ${{matrix.node}}
