on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      
jobs:
  build_affected:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.set_outputs.outputs.tags }}
    name: Dispatch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        uses: ng-easy/npm-setup@v1.7.2
      - name: Run affected
        run: echo ::set-output name=tags::$(npm run --silent ng affected:apps -- --plain --base=origin/main~1 --head=main)
        id: set_outputs
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.1
        with:
          # PowerShell script to execute in Actions-hydrated context
          script: |
            Write-Host $job.steps.set_outputs.output.tags.ToString()
          
  dispatch_event:
      needs: [build_affected]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          affected: ${{ fromJSON(needs.build_affected.outputs.affected) }}
      steps:
        - name: Publish Event
          uses: peter-evans/repository-dispatch@v1.1.3
          with:
            token: ${{ secrets.WORKFLOW_TRIGGER }}
            event-type: ${{matrix.affected}}
