on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      
jobs:
  dipatch:
    runs-on: ubuntu-latest
    env:
      AFFECTED_APPS: ''
    name: Dispatch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        uses: ng-easy/npm-setup@v1.7.2
      - name: Run affected
        run: ${{env.AFFECTED_APPS = $(npm run --silent ng affected:apps -- --plain --base=origin/main~1 --head=main)}} 
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        affected: ['articles','customers']
    steps:
      - name: Test env
        run: echo ${{env.AFFECTED_APPS}}
      - name: Publish Event
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          event-type: ${{matrix.affected}}
