- name: Repository Dispatch
  uses: peter-evans/repository-dispatch@v1
  with:
    token: ${{ secrets.WORKFLOW_TRIGGER }}
    repository: username/my-repo
    event-type: articles
    client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
