on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  dipatch:
    runs-on: ubuntu-latest
    name: Dispatch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      uses: ng-easy/npm-setup@v1.7.2
    - name: Run affected
      run: echo ::set-output name=tags::$(npm run --silent ng affected:apps -- --plain --base=origin/main~1 --head=main)
      id: vars
    - name: Repository Dispatch
      uses: './dispatch.yml'
      with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          eventType: default
    - name: test
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          event-type: default
          client-payload: '{"affected": "${{ steps.vars.outputs.tags }}"}'

