on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      
jobs:
  dipatch:
    runs-on: ubuntu-latest
    name: Dispatch
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          event-type: articles
