on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
env:
  BEFORE_SHA: ${{ github.event.before }}
jobs:
  dipatch:
    runs-on: ubuntu-latest
    name: Dispatch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      uses: ng-easy/npm-setup@v1.7.2
    - name: Run affected
      run: echo ::set-output name=tags::$(npm run --silent ng affected:apps -- --plain --base=$BEFORE_SHA)
      id: vars
    - run: echo "TAGS FOUND ${{ steps.vars.outputs.tags }}"
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          event-type: articles

