on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  dipatch:
    runs-on: ubuntu-latest
    name: Dispatch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      uses: ng-easy/npm-setup@v1.7.2
    - name: Run affected
      shell: bash
      run: |
        export TAGS=$(npm run --silent ng affected:apps -- --plain --base=remotes/origin/main)
        echo "::set-env name=TAGS::$TAGS"
    - run: echo "TAGS FOUND"      
    - run: echo $TAGS      
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1.1.3
      with:
          token: ${{ secrets.WORKFLOW_TRIGGER }}
          event-type: articles

